/**
 * Global layout for the Next.js application.
 *
 * This file sets up the base fonts, injects global styles and wraps the entire
 * application with providers. `AppWrapper` preloads critical assets before
 * rendering children and `LoadingOverlayProvider` exposes a context used to
 * display a loading screen during section transitions.
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import LoadingOverlay from "@/components/layout/LoadingOverlay";
import { LoadingOverlayProvider } from "@/context/LoadingOverlayContext";
import AppWrapper from "@/components/layout/AppWrapper";
import { SmoothScrollProvider } from "@/context/ScrollContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component applied to every page.
 *
 * @param {Readonly<{children: React.ReactNode}>} props React children to render
 * inside the layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScrollProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoadingOverlayProvider>
          <AppWrapper>{children}<LoadingOverlay text="Loading..." />
</AppWrapper>
        </LoadingOverlayProvider>
      </body>
    </html>
    </SmoothScrollProvider>

  );
}
